select * from dual
--INSERT INTO PRODUTO (CODIGO, DESCRICAO) VALUES (10, 'PIZZA');
--INSERT INTO PRODUTO (CODIGO, DESCRICAO) VALUES (20, 'HAMBURGUER');
--INSERT INTO PRODUTO (CODIGO, DESCRICAO) VALUES (30, 'SUSHI');
--INSERT INTO PRODUTO (CODIGO, DESCRICAO) VALUES (40, 'TEMAKI');